service: library-management-system

provider:
  name: aws
  region: us-west-1
  runtime: go1.x
  stage: v1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
            - events:*
            - cloudwatch:*
          Resource: "*"

package:
  patterns:
    - "!./**"
    - "./build/**"

resources:
  Resources:
    books:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: books
        AttributeDefinitions:
          - AttributeName: ibsn
            AttributeType: S
        KeySchema:
          - AttributeName: ibsn
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: uid
            AttributeType: S
        KeySchema:
          - AttributeName: uid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  authorizer:
    name: ${sls:stage}-authorizer
    handler: build/authorizer
  book:
    name: ${sls:stage}-books
    handler: build/book
    events:
      # Get book by ibsn
      - http:
          path: /book/{ibsn}
          method: GET
          cors: true
      #  Get all books
      - http:
          path: /books
          method: GET
          cors: true
      # Create a book
      - http:
          path: /book
          method: POST
          cors: true
      # Update a book
      - http:
          path: /book
          method: PATCH
          cors: true
      # Deletes a book by its ibsn
      - http:
          path: /book/{ibsn}
          method: DELETE
          cors: true
  user:
    name: ${sls:stage}-users
    handler: build/user
    events:
      # Get user by uid
      - http:
          path: /user/{uid}
          method: GET
          cors: true
      #  Get all users
      - http:
          path: /users
          method: GET
          cors: true
      # Create a user
      - http:
          path: /user
          method: POST
          cors: true
      # login
      - http:
          path: /login
          method: POST
          cors: true
      # Update a user
      - http:
          path: /user
          method: PATCH
          cors: true
      # Deletes a user by its uid
      - http:
          path: /user/{uid}
          method: DELETE
          cors: true
  book-actions:
    name: ${sls:stage}-book-actions
    handler: build/book_actions
    events:
      - http:
          path: /checkout/{ibsn}
          method: POST
          cors: true
          authorizer: ${self:custom.authorizer.users}
      - http:
          path: /return/{ibsn}
          method: POST
          cors: true
          authorizer: ${self:custom.authorizer.users}


custom:
  authorizer:
    users:
      name: authorizer
      type: TOKEN
      identitySource: method.request.header.Authorization
      identityValidationExpression: Bearer (.*)